In [ ]:
# Importing

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
ball_by = "/content/IPL_Ball_by_Ball_2008_2022.csv"
ball_by = pd.read_csv(ball_by)
ball_by.head(3)

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals

In [ ]:
matches = "/content/IPL_Matches_2008_2022.csv"
matches = pd.read_csv(matches)
matches.head(10)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
5,1304115,Mumbai,2022-05-21,2022,69,Delhi Capitals,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai Indians,field,N,Mumbai Indians,Wickets,5.0,NaN,JJ Bumrah,"['PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant'...","['Ishan Kishan', 'RG Sharma', 'D Brevis', 'Til...",Nitin Menon,Tapan Sharma
6,1304114,Mumbai,2022-05-20,2022,68,Chennai Super Kings,Rajasthan Royals,"Brabourne Stadium, Mumbai",Chennai Super Kings,bat,N,Rajasthan Royals,Wickets,5.0,NaN,R Ashwin,"['RD Gaikwad', 'DP Conway', 'MM Ali', 'N Jagad...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,NA Patwardhan
7,1304113,Mumbai,2022-05-19,2022,67,Gujarat Titans,Royal Challengers Bangalore,"Wankhede Stadium, Mumbai",Gujarat Titans,bat,N,Royal Challengers Bangalore,Wickets,8.0,NaN,V Kohli,"['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...","['V Kohli', 'F du Plessis', 'GJ Maxwell', 'KD ...",KN Ananthapadmanabhan,GR Sadashiv Iyer
8,1304112,Navi Mumbai,2022-05-18,2022,66,Lucknow Super Giants,Kolkata Knight Riders,"Dr DY Patil Sports Academy, Mumbai",Lucknow Super Giants,bat,N,Lucknow Super Giants,Runs,2.0,NaN,Q de Kock,"['Q de Kock', 'KL Rahul', 'E Lewis', 'DJ Hooda...","['VR Iyer', 'A Tomar', 'N Rana', 'SS Iyer', 'S...",R Pandit,YC Barde
9,1304111,Mumbai,2022-05-17,2022,65,Sunrisers Hyderabad,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai Indians,field,N,Sunrisers Hyderabad,Runs,3.0,NaN,RA Tripathi,"['Abhishek Sharma', 'PK Garg', 'RA Tripathi', ...","['RG Sharma', 'Ishan Kishan', 'DR Sams', 'Tila...",CB Gaffaney,N Pandit

In [ ]:
# Checking shape
print("ball_by_ball shape",ball_by.shape)
print("matches shape",matches.shape)

ball_by_ball shape (225954, 17)
matches shape (950, 20)

In [ ]:
# Checcking dtypes
# ball_by_ball dtypes

ball_by.dtypes

ID                    int64
innings               int64
overs                 int64
ballnumber            int64
batter               object
bowler               object
non-striker          object
extra_type           object
batsman_run           int64
extras_run            int64
total_run             int64
non_boundary          int64
isWicketDelivery      int64
player_out           object
kind                 object
fielders_involved    object
BattingTeam          object
dtype: object

In [ ]:
# matches dtypes

matches.dtypes

ID                   int64
City                object
Date                object
Season              object
MatchNumber         object
Team1               object
Team2               object
Venue               object
TossWinner          object
TossDecision        object
SuperOver           object
WinningTeam         object
WonBy               object
Margin             float64
method              object
Player_of_Match     object
Team1Players        object
Team2Players        object
Umpire1             object
Umpire2             object
dtype: object

In [ ]:
# Changing the dtype of matche's date  column

matches['Date'] = pd.to_datetime(matches['Date'],format='%m/%d/%Y',errors='coerce')
matches.dtypes

ID                          int64
City                       object
Date               datetime64[ns]
Season                     object
MatchNumber                object
Team1                      object
Team2                      object
Venue                      object
TossWinner                 object
TossDecision               object
SuperOver                  object
WinningTeam                object
WonBy                      object
Margin                    float64
method                     object
Player_of_Match            object
Team1Players               object
Team2Players               object
Umpire1                    object
Umpire2                    object
dtype: object

In [ ]:
# Checking null values
# ball_by_ball

ball_by.isna().sum()

ID                        0
innings                   0
overs                     0
ballnumber                0
batter                    0
bowler                    0
non-striker               0
extra_type           213905
batsman_run               0
extras_run                0
total_run                 0
non_boundary              0
isWicketDelivery          0
player_out           214803
kind                 214803
fielders_involved    217966
BattingTeam               0
dtype: int64

In [ ]:
# matches

matches.isnull().sum()

ID                   0
City                51
Date               950
Season               0
MatchNumber          0
Team1                0
Team2                0
Venue                0
TossWinner           0
TossDecision         0
SuperOver            4
WinningTeam          4
WonBy                0
Margin              18
method             931
Player_of_Match      4
Team1Players         0
Team2Players         0
Umpire1              0
Umpire2              0
dtype: int64

In [ ]:
# checking duplicates

matches[matches.duplicated()]

Empty DataFrame
Columns: [ID, City, Date, Season, MatchNumber, Team1, Team2, Venue, TossWinner, TossDecision, SuperOver, WinningTeam, WonBy, Margin, method, Player_of_Match, Team1Players, Team2Players, Umpire1, Umpire2]
Index: []

In [ ]:

ball_by[ball_by.duplicated()]

Empty DataFrame
Columns: [ID, innings, overs, ballnumber, batter, bowler, non-striker, extra_type, batsman_run, extras_run, total_run, non_boundary, isWicketDelivery, player_out, kind, fielders_involved, BattingTeam]
Index: []

In [ ]:
# mergining the both ball_by_ball and matches

merged_df = pd.merge(matches,ball_by, on = 'ID')
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 225954 entries, 0 to 225953
Data columns (total 36 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ID                 225954 non-null  int64
 1   City               213557 non-null  object
 2   Date               0 non-null       datetime64[ns]
 3   Season             225954 non-null  object
 4   MatchNumber        225954 non-null  object
 5   Team1              225954 non-null  object
 6   Team2              225954 non-null  object
 7   Venue              225954 non-null  object
 8   TossWinner         225954 non-null  object
 9   TossDecision       225954 non-null  object
 10  SuperOver          225582 non-null  object
 11  WinningTeam        225582 non-null  object
 12  WonBy              225954 non-null  object
 13  Margin             221948 non-null  float64
 14  method             3208 non-null    object
 15  Player_of_Match    225582 non-null  object
 16  Team1Players       225954 non-null  object
 17  Team2Players       225954 non-null  object
 18  Umpire1            225954 non-null  object
 19  Umpire2            225954 non-null  object
 20  innings            225954 non-null  int64
 21  overs              225954 non-null  int64
 22  ballnumber         225954 non-null  int64
 23  batter             225954 non-null  object
 24  bowler             225954 non-null  object
 25  non-striker        225954 non-null  object
 26  extra_type         12049 non-null   object
 27  batsman_run        225954 non-null  int64
 28  extras_run         225954 non-null  int64
 29  total_run          225954 non-null  int64
 30  non_boundary       225954 non-null  int64
 31  isWicketDelivery   225954 non-null  int64
 32  player_out         11151 non-null   object
 33  kind               11151 non-null   object
 34  fielders_involved  7988 non-null    object
 35  BattingTeam        225954 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(9), object(25)
memory usage: 63.8+ MB

In [ ]:
# 1. From overs 0-19, which over has the most runs scored in, on average?

ball_by.groupby('overs')['total_run'].mean().idxmax()

19

In [ ]:
# 2. Top 10 umpires, who were part of the most matches

matches['Umpire1'].append(matches['Umpire2']).value_counts().nlargest(10)

<ipython-input-58-6edf03253fe0>:3: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  matches['Umpire1'].append(matches['Umpire2']).value_counts().nlargest(10)

S Ravi                   131
AK Chaudhary             111
HDPK Dharmasena           94
C Shamshuddin             88
Nitin Menon               83
CB Gaffaney               69
M Erasmus                 67
CK Nandan                 59
BNJ Oxenford              57
KN Ananthapadmanabhan     56
dtype: int64

In [ ]:
#3. Which team has the highest probability of winning a match given that they had won the toss?

toss_and_won = matches[matches['TossWinner'] == matches['WinningTeam']]
winning_probability = (toss_and_won['TossWinner'].value_counts()/matches['TossWinner'].value_counts()).nlargest(1)
winning_probability

Rising Pune Supergiant    0.833333
Name: TossWinner, dtype: float64

In [ ]:
#4. Top 10 most successful bowlers in terms of number of wickets taken

ball_by[ball_by['isWicketDelivery'] == 1]['bowler'].value_counts().nlargest(10)

DJ Bravo           207
SL Malinga         188
A Mishra           175
R Ashwin           174
YS Chahal          172
SP Narine          171
PP Chawla          165
B Kumar            165
Harbhajan Singh    161
JJ Bumrah          161
Name: bowler, dtype: int64

In [ ]:
#5. Calculate for each team the number of playoff matches played.

playoff = matches[matches['MatchNumber'].isin(['Qualifier 2','Qualifier 1','Qualifier','3rd Place Play-Off'])]
teams_playoff = playoff['Team1'].append(playoff['Team2'])
teams_playoff.value_counts()

<ipython-input-69-b979117ae84f>:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  teams_playoff = playoff['Team1'].append(playoff['Team2'])

Chennai Super Kings            10
Mumbai Indians                  8
Royal Challengers Bangalore     6
Delhi Capitals                  5
Kolkata Knight Riders           5
Sunrisers Hyderabad             4
Rajasthan Royals                3
Gujarat Lions                   2
Kings XI Punjab                 2
Delhi Daredevils                2
Gujarat Titans                  1
Rising Pune Supergiant          1
Deccan Chargers                 1
dtype: int64

In [ ]:
# 6. On which venue, the team batting second has the most advantage?

# found that Team1 has done batting first

matches[matches['WinningTeam'] == matches['Team2']]['Venue'].value_counts().idxmax()

'Feroz Shah Kotla'

In [ ]:
# 7. Which batsman in the history of IPL has been caught out the most?

ball_by[ball_by['kind'] == 'caught'].groupby('player_out')['kind'].value_counts().nlargest(1)

player_out  kind
RG Sharma   caught    135
Name: kind, dtype: int64

In [ ]:
# 8. Which bowler has taken the wicket of the batsman in que no. 7?

ball_by[ball_by['player_out'] == 'RG Sharma'].groupby('bowler')['isWicketDelivery'].size().idxmax()

'A Mishra'